### ISSUE TITLE
Make dependency to request_kerberos optional

### ISSUE THREAD

**Issue by ggreg** [prestodb/presto-python-client#65]
[`prestodb.auth`](https://github.com/prestodb/presto-python-client/blob/master/prestodb/auth.py) module provides a concrete class to setup Kerberos authentication. It requires the dependency *requests_kerberos* that eventually depends on a native library. This native library introduces complexity to build presto-python-client whereas most people don't need it. The purpose of this issue is to relax the requirement on *request_kerberos* while providing an easy to request it.

**Comment by xerial** [comment]
We also had the same issue when trying to use this client on Google Colaboratory https://colab.research.google.com

It would be great if you can make it an optional requirement.

**Comment by ggreg** [comment]
@xerial This should land soon!

**Comment by xerial** [comment]
@ggreg Thanks. FYI, ibis project is already implementing this approach by preparing a flag for optional installation of kerberos module: 
https://github.com/ibis-project/ibis/blob/master/setup.py#L27
