### ISSUE TITLE
latest version not pushed to pypi

### ISSUE THREAD

**Issue by mayankjuneja** [prestodb/presto-python-client#66]
Hi, can someone please push the latest version (0.5.x) to pypi? The latest version available on [pypi](https://pypi.org/project/presto-python-client/#history) is 0.4.2. Also, looks like https://github.com/prestodb/presto-python-client/pull/53 is not part of the latest release.

Thanks!

**Comment by tnesztler** [comment]
In the mean time, you can install it from the GitHub repository using pipenv `presto-python-client = {git = "https://github.com/prestodb/presto-python-client", ref = "3ab5b69"}` and pinning it to the commit fixing #53.

**Comment by shaswatshah** [comment]
Bump. Running into requirements conflict because of this

**Comment by ggreg** [comment]
#53 was merged [after](https://github.com/prestodb/presto-python-client/commits/master) 0.5.0. I'll publish a version, most likely 0.5.1, that includes it tonight.

**Comment by ggreg** [comment]
Uploaded 0.5.1 https://pypi.org/project/presto-python-client/#files
