### ISSUE TITLE
Expose query status from cursor

### ISSUE THREAD

**Issue by UglyTroLL** [prestodb/presto-python-client#7]
Would be awesome if we can get the query status from cursor, like the nextUri

**Comment by ggreg** [comment]
Can you describe some use cases you would like to handle?

**Comment by UglyTroLL** [comment]
@ggreg Yes sure, basically, we want to be able to track the progress (and the presto tracking url) after the query start running, but currently there is no way to get that from `Cursor` if I'm correct? Thanks!

**Comment by highker** [comment]
Resolved https://github.com/prestodb/presto-python-client/pull/17
