### ISSUE TITLE
v0.6.0 is not released to pypi

### ISSUE THREAD

**Issue by takuti** [prestodb/presto-python-client#76]
Can you push the latest version to PyPI?

https://pypi.org/project/presto-python-client/

Workaround:

```
git+https://github.com/prestodb/presto-python-client.git@0.6.0#egg=presto_python_client
```

**Comment by takuti** [comment]
@ggreg Ping...

**Comment by anant-g** [comment]
Could not find a version that satisfies the requirement presto-python-client===0.6.0 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.5.1)
No matching distribution found for presto-python-client===0.6.0

**Comment by ggreg** [comment]
It is available now https://pypi.org/project/presto-python-client/

**Comment by ggreg** [comment]
Thanks for you patience and sorry for the delay
