### ISSUE TITLE
Got PERMISSION_DENIED USER_ERROR while executing query

### ISSUE THREAD

**Issue by FeiZou** [prestodb/presto-python-client#95]
Hey guys, I'm new to Presto and I'm trying to play around with it using presto-python-client. I successfully built the connection but when I run some basic `SELECT` queries like `SELECT COUNT(*) from <table_name>` I got following Error: `PrestoUserError(type=USER_ERROR, name=PERMISSION_DENIED, message="Access Denied: Cannot select from table <schema_name.table_name> ", query_id=*******)`. I already executed `cur.execute("set role admin")` before executing any query and it returned `true` to me.  

Anyone can help me with this problem?

**Comment by FeiZou** [comment]
Looks like `set role admin` doesn't really worked. I can see clearly that `cur.execute("set role admin")` return `true` to me, but the privilege got lost when next query got executed.

**Comment by FeiZou** [comment]
Wait, maybe I should ask whether this library supports `set role` operation first?

**Comment by moiz-frost** [comment]
@FeiZou I see that you closed this. Were you able to come up with a solution?
